### ISSUE TITLE
tab header container not having left margin

### ISSUE THREAD

**Issue by iwa** [iwa/Sei#28]
**Screenshots**

<img width="120" alt="Image" src="https://github.com/user-attachments/assets/cdfc3b4a-d281-4ee2-93af-897a0a3dd0df" />

**Comment by iwa** [comment]
macos specific it seems

```css
.is-hidden-frameless:not(.is-fullscreen) .workspace-tabs.mod-top-left-space .workspace-tab-header-container {
    padding-left: calc(var(--size-4-4) + var(--frame-left-space));
}
```
